### ISSUE TITLE
[Suggestion] Make Blocking Instant

### ISSUE THREAD

**Issue by RobertHDPotatoes** [someaddons/Shieldmechanics#10]
Not sure if you are accepting suggestions for this mod but I have a cool idea that I think would fit right in.

Right now, in vanilla Minecraft there is a gap between when you go from simply holding the shield to when you are blocking with a shield (issue 100949 on Mojang's bug tracker https://bugs.mojang.com/browse/MC-100949). To the player, when they right-click to block with the shield, they can be hit both during the shield draw animation, AND a short period after where the shield is fully drawn!

My suggestion is to remove that gap of time, and make blocking work instantly upon right click (even during the shield draw animation), maybe with a toggle option to disable/enable the change in the config?

**Comment by someaddons** [comment]
ye I know about that mojang bug, though I kinda feel its not bad that shields have a slight activation delay aswell makes it a bit more realistic/immersive. Like imagine handling a big shield to hide behind its gonna take a bit to get it into position. Also what I'd need to do to fix it is make shields a coremod, as atm it doesnt use any coremodding which may delay further version updates since its then dependent on the coremod lib

**Comment by RobertHDPotatoes** [comment]
Fair enough
