### ISSUE TITLE
[Bug]: Crashing when entering world. (Version is 1.19!, can't change that inside issue)

### ISSUE THREAD

**Issue by murao-kun** [someaddons/Shieldmechanics#13]
### Describe the bug you're experiencing

Trying to join my singleplayer world and getting crashed.

### Reproducability

I really don't know how.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/murao-kun/a3bdfed76019bcbc823302c941ac606a

**Comment by someaddons** [comment]
Can't reproduce this with just shields & 1.19, must be some sort of mod conflict

**Comment by krjencik** [comment]
Minecraft 1.19.2 Forge 43.0.7:
[latest.log](https://github.com/someaddons/Shieldmechanics/files/9297871/latest.log)

**Comment by someaddons** [comment]
if you find which mod is conflicting I'll look into it

**Comment by someaddons** [comment]
Try version 3.4, that one may fix it

**Comment by murao-kun** [comment]
Still happening, on 3.4 too.
[crash-2022-08-11_22.28.17-server.txt](https://github.com/someaddons/Shieldmechanics/files/9311506/crash-2022-08-11_22.28.17-server.txt)

**Comment by krjencik** [comment]
The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.getModEventBus()" because the return value of "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get()" is null
Exit Code: -1

[crash-2022-08-12_11.49.37-server.txt](https://github.com/someaddons/Shieldmechanics/files/9315433/crash-2022-08-12_11.49.37-server.txt)

**Comment by someaddons** [comment]
try 3.5

**Comment by murao-kun** [comment]
Fixed in 3.5.
