### ISSUE TITLE
[Bug]: Crashing on Startup

### ISSUE THREAD

**Issue by MihanDeNoob** [someaddons/Shieldmechanics#18]
### Describe the bug you're experiencing

self explanatory

### Reproducability

Fabric 1.20.1 
Fabric loader 0.16.4

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://mclo.gs/hgJfg3n

**Comment by someaddons** [comment]
You must have some weirdly broken coremods in that pack to make this crash possible, since it crashes because it does not find a value in a map which right before was put into the very same map. Nonetheless I improved the surrounding code  a bit so the lookup where it crashed is no longer necessary. 
"Fixed" in 4.5 I guess :D

**Comment by MihanDeNoob** [comment]
Its my personal carefully assembled modpack that im still working on (300+mods and 570 if you count the libraries). So far ive solved all my issues and everything works, well, besides some mods having their own bugs for devs to fix.

**Comment by MihanDeNoob** [comment]
Can confirm that the issue is indeed fixed! Thank you for the fast response <3
